"""Content marketing models (M3.2): generated content, EDM campaigns, SEO records.

All rows are workspace-scoped. Content generation (selling points, SEO articles,
EDM drafts) follows an approval workflow (draft -> pending -> approved -> published
/ rejected). EDM campaigns track send metrics. SEO records capture keyword strategy
and ranking snapshots.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import uuid4

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import AI_JSON, Base, TimestampMixin, WorkspaceMixin

# Content types generated by the marketing AI.
CONTENT_TYPES: tuple[str, ...] = (
    "product_selling_points",
    "product_description",
    "seo_article",
    "edm_abandoned_cart",
    "edm_repurchase",
    "edm_welcome",
    "edm_newsletter",
    "ad_copy",
    "social_post",
)

# Content approval workflow states.
CONTENT_STATUSES: tuple[str, ...] = (
    "draft",
    "pending_review",
    "approved",
    "rejected",
    "published",
    "archived",
)

# EDM campaign types.
EDM_CAMPAIGN_TYPES: tuple[str, ...] = (
    "abandoned_cart",
    "post_purchase",
    "welcome",
    "newsletter",
    "promotional",
    "win_back",
    "review_request",
    "replenishment",
)

# EDM campaign statuses.
EDM_STATUSES: tuple[str, ...] = (
    "draft",
    "scheduled",
    "active",
    "paused",
    "completed",
    "cancelled",
)


class ContentItem(Base, TimestampMixin, WorkspaceMixin):
    """A generated content item with approval workflow (M3.2).

    Covers product selling points, SEO articles, EDM drafts, ad copy, etc.
    ``content_json`` holds the structured output (title, body, keywords, etc.);
    ``quality_score`` is the AI self-evaluation or rule-based score.
    """

    __tablename__ = "content_items"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    content_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)
    content_json: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="draft", index=True)
    language: Mapped[str] = mapped_column(String(8), nullable=False, default="en")
    keywords: Mapped[list[str]] = mapped_column(AI_JSON, nullable=False, default=list)
    quality_score: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    approved_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rejection_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    source: Mapped[str] = mapped_column(String(32), nullable=False, default="ai_generated")
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_content_workspace_type_status", "workspace_id", "content_type", "status"),
        Index("ix_content_workspace_product", "workspace_id", "product_id"),
    )


class EDMCampaign(Base, TimestampMixin, WorkspaceMixin):
    """An EDM / email marketing campaign with send metrics (M3.2).

    Tracks the campaign lifecycle and aggregate metrics (sent, opened, clicked,
    converted, revenue). ``flow_config`` holds the automated flow steps
    (delay, template, discount) for triggered campaigns.
    """

    __tablename__ = "edm_campaigns"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    campaign_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="draft", index=True)
    subject: Mapped[str | None] = mapped_column(String(500), nullable=True)
    from_name: Mapped[str] = mapped_column(String(128), nullable=False, default="Nuotao Outdoor")
    from_email: Mapped[str] = mapped_column(String(255), nullable=False, default="noreply@nuotaooutdoor.com")
    template_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    content_json: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    flow_config: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    segment_filter: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    # Send metrics (aggregate).
    total_sent: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_delivered: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_opened: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_clicked: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_converted: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_unsubscribed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    revenue_attributed: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0)
    currency: Mapped[str] = mapped_column(String(8), nullable=False, default="USD")
    scheduled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_edm_workspace_type_status", "workspace_id", "campaign_type", "status"),
    )

    @property
    def open_rate(self) -> float:
        if self.total_delivered == 0:
            return 0.0
        return round(self.total_opened / self.total_delivered, 4)

    @property
    def click_rate(self) -> float:
        if self.total_delivered == 0:
            return 0.0
        return round(self.total_clicked / self.total_delivered, 4)

    @property
    def conversion_rate(self) -> float:
        if self.total_delivered == 0:
            return 0.0
        return round(self.total_converted / self.total_delivered, 4)


class SEORecord(Base, TimestampMixin, WorkspaceMixin):
    """SEO keyword and ranking record (M3.2).

    Captures keyword strategy, target pages, and ranking snapshots over time.
    ``ranking_history`` is a list of {date, position, url} snapshots.
    """

    __tablename__ = "seo_records"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    keyword: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    target_url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    target_page_type: Mapped[str] = mapped_column(String(32), nullable=False, default="product")
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    language: Mapped[str] = mapped_column(String(8), nullable=False, default="en")
    country: Mapped[str] = mapped_column(String(8), nullable=False, default="US")
    search_volume: Mapped[int | None] = mapped_column(Integer, nullable=True)
    keyword_difficulty: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    current_position: Mapped[int | None] = mapped_column(Integer, nullable=True)
    best_position: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ranking_history: Mapped[list[dict[str, Any]]] = mapped_column(AI_JSON, nullable=False, default=list)
    meta_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    meta_description: Mapped[str | None] = mapped_column(String(500), nullable=True)
    structured_data_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="active", index=True)
    notes: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_seo_workspace_keyword", "workspace_id", "keyword"),
        Index("ix_seo_workspace_status", "workspace_id", "status"),
        Index("ix_seo_workspace_product", "workspace_id", "product_id"),
    )
