"""AI Creative Studio models (v0.17 C0).

Four core tables that form the Creative Studio data foundation:
- CreativeBrief: structured brief for creative production, derived from
  Product Master facts.  One brief can require multiple asset types.
- CreativeAsset: one visual asset (image) with version, QC result and
  compliance result.  Every asset is workspace-scoped and traceable.
- CreativeGenerationRun: records one AI generation or edit operation,
  including provider, model, prompt, parameters, cost and trace.
- CreativeReview: audit trail for AI or human review decisions on assets.

All models follow the Nuotao pattern: workspace_id scoping, UUID primary
keys, timezone-aware datetimes, JSONB for flexible AI data, and trace_id
for audit.
"""

from __future__ import annotations

from datetime import datetime, UTC
from decimal import Decimal
from typing import Any
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import AI_JSON, Base, TimestampMixin, WorkspaceMixin

__all__ = [
    "CreativeApprovalRequest",
    "CreativeBrief",
    "CreativeCalibrationRun",
    "CreativeCostEvent",
    "CreativeGenerationRun",
    "CreativeKnowledgeEntry",
    "CreativePromptTemplate",
    "CreativeReview",
    "CreativeStudioAsset",
    "ASSET_SOURCE_TYPES",
    "ASSET_STATUSES",
    "BRIEF_STATUSES",
    "BRIEF_TYPES",
    "CREATIVE_KNOWLEDGE_TYPES",
    "GENERATION_STATUSES",
    "PROMPT_TEMPLATE_STATUSES",
    "REVIEWER_TYPES",
]

# ---------------------------------------------------------------------------
# Enums (stored as plain strings; validate in service layer)
# ---------------------------------------------------------------------------

BRIEF_TYPES: tuple[str, ...] = (
    "product_hero",       # single hero image
    "lifestyle_scene",    # lifestyle scene
    "detail_scene",       # detail page illustration
    "infographic",        # infographic
    "dimension_visual",   # dimension / spec visual
    "banner",             # banner / ad creative
    "social_vertical",    # social media vertical
    "background_replace", # image editing: bg replace
    "background_remove",  # image editing: bg remove
    "color_variant",      # image editing: color variant
    "upscale",            # image editing: upscale
    "batch_listing_set",  # batch: full listing image set
)

BRIEF_STATUSES: tuple[str, ...] = (
    "DRAFT",
    "IN_PROGRESS",
    "COMPLETED",
    "ARCHIVED",
)

ASSET_SOURCE_TYPES: tuple[str, ...] = (
    "ORIGINAL",       # uploaded / manually created
    "AI_GENERATED",   # generated by AI
    "AI_EDITED",      # edited by AI
    "IMPORTED",       # imported from external source
)

ASSET_STATUSES: tuple[str, ...] = (
    "DRAFT",
    "GENERATED",
    "QC_PASSED",
    "PENDING_REVIEW",
    "APPROVED",
    "REJECTED",
    "ARCHIVED",
)

GENERATION_STATUSES: tuple[str, ...] = (
    "QUEUED",
    "RUNNING",
    "SUCCEEDED",
    "FAILED",
    "CANCELLED",
)

REVIEWER_TYPES: tuple[str, ...] = (
    "AI",
    "HUMAN",
)


# ---------------------------------------------------------------------------
# CreativeBrief
# ---------------------------------------------------------------------------


class CreativeBrief(Base, TimestampMixin, WorkspaceMixin):
    """Structured brief for creative production (v0.17 C0).

    A brief is derived from Product Master data: product facts, target
    market, channel, visual style rules, and required asset types.
    One brief can drive multiple generation runs and produce multiple
    creative assets.

    ``required_assets`` is a JSONB list of asset specifications, e.g.::

        [
            {"type": "hero_image", "count": 3, "prompt": "...", "aspect_ratio": "1:1"},
            {"type": "lifestyle", "count": 2, "prompt": "...", "aspect_ratio": "4:3"},
        ]

    ``constraints`` is a JSONB dict of production constraints, e.g.::

        {
            "budget_cny": 5.00,
            "max_retries": 2,
            "approval_required": True,
        }
    """

    __tablename__ = "creative_briefs"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    listing_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("listing_jobs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    brief_type: Mapped[str] = mapped_column(String(32), nullable=False, default="product_hero")
    objective: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_market: Mapped[str | None] = mapped_column(String(64), nullable=True)
    channel: Mapped[str | None] = mapped_column(String(32), nullable=True)
    visual_style: Mapped[str | None] = mapped_column(String(128), nullable=True)
    required_assets: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=list
    )
    constraints: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="DRAFT")
    created_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approved_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_creative_briefs_workspace_status", "workspace_id", "status"),
        Index("ix_creative_briefs_workspace_product", "workspace_id", "product_id"),
        Index("ix_creative_briefs_workspace_type", "workspace_id", "brief_type"),
    )


# ---------------------------------------------------------------------------
# CreativeAsset
# ---------------------------------------------------------------------------


class CreativeStudioAsset(Base, TimestampMixin, WorkspaceMixin):
    """One visual asset (image) with version and QC metadata (v0.17 C0).

    Every asset is workspace-scoped and traceable.  The ``storage_key``
    points to the object in storage (S3 / local path / signed URL).  The
    ``version`` column supports iterative edits: a new version creates a
    new row linked via ``parent_asset_id``.

    ``quality_result`` and ``compliance_result`` are JSONB dicts that
    store QC and compliance check results.  An asset can only be
    APPROVED if QC passes.
    """

    __tablename__ = "creative_studio_assets"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    brief_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_briefs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    parent_asset_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_studio_assets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    asset_type: Mapped[str] = mapped_column(String(32), nullable=False, default="hero_image")
    source_type: Mapped[str] = mapped_column(String(16), nullable=False, default="AI_GENERATED")
    storage_key: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    preview_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ratio: Mapped[str | None] = mapped_column(String(16), nullable=True)
    mime_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    generation_run_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_generation_runs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="DRAFT")
    quality_result: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    compliance_result: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    created_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    reviewed_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # P0-6: WooCommerce push tracking for idempotency
    wc_pushed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    wc_media_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    __table_args__ = (
        Index("ix_creative_studio_assets_workspace_status", "workspace_id", "status"),
        Index("ix_creative_studio_assets_workspace_product", "workspace_id", "product_id"),
        Index("ix_creative_studio_assets_workspace_brief", "workspace_id", "brief_id"),
        Index("ix_creative_studio_assets_workspace_parent", "workspace_id", "parent_asset_id"),
        # P0-6: Index for WC push tracking
        Index("ix_creative_studio_assets_wc_pushed", "workspace_id", "wc_pushed_at"),
    )


# ---------------------------------------------------------------------------
# CreativeGenerationRun
# ---------------------------------------------------------------------------


class CreativeGenerationRun(Base, TimestampMixin, WorkspaceMixin):
    """One AI generation or edit operation (v0.17 C0).

    Records the full lifecycle of a single generation call: provider,
    model, input assets, prompt, parameters, output assets, status,
    cost and trace.  Cost is recorded in CNY for budget tracking.

    ``input_asset_ids`` and ``output_asset_ids`` are JSONB lists of UUIDs
    that link this run to the creative_studio_assets it consumed and produced.
    """

    __tablename__ = "creative_generation_runs"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    brief_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_briefs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    operation: Mapped[str] = mapped_column(String(32), nullable=False, default="generate")
    provider: Mapped[str | None] = mapped_column(String(64), nullable=True)
    model: Mapped[str | None] = mapped_column(String(128), nullable=True)
    input_asset_ids: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=list
    )
    prompt_template_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    prompt_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    parameters: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    output_asset_ids: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=list
    )
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="QUEUED")
    provider_request_id: Mapped[str | None] = mapped_column(String(256), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    input_units: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_units: Mapped[int | None] = mapped_column(Integer, nullable=True)
    estimated_cost: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    actual_cost: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(64), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    dedup_key: Mapped[str | None] = mapped_column(
        String(128), nullable=True, unique=True, index=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("ix_creative_runs_workspace_status", "workspace_id", "status"),
        Index("ix_creative_runs_workspace_product", "workspace_id", "product_id"),
        Index("ix_creative_runs_workspace_brief", "workspace_id", "brief_id"),
        Index("ix_creative_runs_workspace_model", "workspace_id", "model"),
        # P0-5: Unique constraint on dedup_key for idempotency
        Index("ix_creative_runs_dedup_key", "dedup_key", unique=True),
    )


# ---------------------------------------------------------------------------
# CreativeReview
# ---------------------------------------------------------------------------


class CreativeReview(Base, TimestampMixin, WorkspaceMixin):
    """Review decision on a creative asset (v0.17 C0).

    Audit trail for AI or human review.  Every review record stores the
    decision, reasons, and reviewer identity.  Reviews are immutable once
    written — corrections create a new review row.

    ``review_type`` can be ``quality_check``, ``compliance_check``, or
    ``human_review``.  ``result`` is ``approved`` or ``rejected``.
    """

    __tablename__ = "creative_reviews"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    asset_id: Mapped[Uuid] = mapped_column(
        Uuid,
        ForeignKey("creative_studio_assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    review_type: Mapped[str] = mapped_column(String(32), nullable=False, default="human_review")
    reviewer_type: Mapped[str] = mapped_column(String(16), nullable=False, default="HUMAN")
    result: Mapped[str] = mapped_column(String(16), nullable=False, default="approved")
    reasons: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=list
    )
    reviewer_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_creative_reviews_workspace_asset", "workspace_id", "asset_id"),
        Index("ix_creative_reviews_workspace_type", "workspace_id", "review_type"),
        Index("ix_creative_reviews_workspace_result", "workspace_id", "result"),
    )


# ---------------------------------------------------------------------------
# CreativePromptTemplate
# ---------------------------------------------------------------------------

PROMPT_TEMPLATE_STATUSES: tuple[str, ...] = (
    "DRAFT",
    "ACTIVE",
    "ARCHIVED",
)


class CreativePromptTemplate(Base, TimestampMixin, WorkspaceMixin):
    """Reusable AI prompt template for creative generation (v0.17 C2).

    Templates are versioned and categorized by asset type and product
    category.  Each template stores the prompt text, variables, default
    parameters, and metadata for quality tracking.

    Templates are used by ``CreativeGenerationRun`` via
    ``prompt_template_id`` and ``prompt_version``.  The actual prompt
    text is rendered at execution time by substituting ``variables``.
    """

    __tablename__ = "creative_prompt_templates"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    template_key: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    asset_type: Mapped[str] = mapped_column(String(32), nullable=False, default="hero_image")
    category: Mapped[str] = mapped_column(String(64), nullable=False, default="general")
    prompt_text: Mapped[str] = mapped_column(Text, nullable=False)
    variables: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    default_parameters: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    version: Mapped[str] = mapped_column(String(32), nullable=False, default="1.0.0")
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="DRAFT")
    quality_score: Mapped[Decimal | None] = mapped_column(Numeric(3, 2), nullable=True)
    usage_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_creative_templates_workspace_key", "workspace_id", "template_key"),
        Index("ix_creative_templates_workspace_category", "workspace_id", "category"),
        Index("ix_creative_templates_workspace_status", "workspace_id", "status"),
    )


# ---------------------------------------------------------------------------
# Creative Knowledge Entry (C7)
# ---------------------------------------------------------------------------

CREATIVE_KNOWLEDGE_TYPES: tuple[str, ...] = (
    "success_pattern",      # patterns from successful creative assets
    "failure_pattern",      # patterns from failed/rejected assets
    "style_pattern",        # visual style patterns
    "prompt_pattern",       # effective prompt patterns
    "fidelity_pattern",     # product fidelity patterns
    "ecommerce_pattern",    # e-commerce readiness patterns
    "best_practice",        # general best practices
    "lesson_learned",       # specific lessons from incidents
)


class CreativeKnowledgeEntry(Base, TimestampMixin, WorkspaceMixin):
    """Creative knowledge memory (C7): patterns learned from creative assets.

    Entry types: ``success_pattern`` / ``failure_pattern`` / ``style_pattern`` /
    ``prompt_pattern`` / ``fidelity_pattern`` / ``ecommerce_pattern`` /
    ``best_practice`` / ``lesson_learned``.

    Knowledge entries accumulate patterns from creative reviews, QC results,
    and human feedback. They can be queried by product category, asset type,
    or tags so the Creative Agent can be grounded in evidence when generating
    new creative briefs and prompts.
    """

    __tablename__ = "creative_knowledge_entries"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    asset_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_studio_assets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    brief_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_briefs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    category: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    asset_type: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    entry_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    tags: Mapped[list[Any]] = mapped_column(AI_JSON, nullable=False, default=list)
    source: Mapped[str] = mapped_column(String(32), nullable=False, default="manual")
    confidence: Mapped[Decimal] = mapped_column(Numeric(6, 4), nullable=False, default=0)
    success_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    failure_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_creative_knowledge_workspace_category", "workspace_id", "category"),
        Index("ix_creative_knowledge_workspace_product", "workspace_id", "product_id"),
        Index("ix_creative_knowledge_workspace_asset", "workspace_id", "asset_id"),
        Index("ix_creative_knowledge_workspace_type", "workspace_id", "entry_type"),
        Index("ix_creative_knowledge_workspace_asset_type", "workspace_id", "asset_type"),
    )


# ---------------------------------------------------------------------------
# Creative Calibration Run (C8)
# ---------------------------------------------------------------------------


class CreativeCalibrationRun(Base, TimestampMixin, WorkspaceMixin):
    """Creative calibration proposal (C8): discovered patterns, human-approved.

    Deterministically aggregates successful/failure patterns from creative
    knowledge entries, QC results, and review outcomes. **Never modifies
    creative rules automatically**: the run stays ``proposed`` until a human
    approves or rejects it, and approval only records the decision.

    Calibration outputs include:
    - High-performing prompt templates and styles
    - Common failure patterns to avoid
    - Recommended parameter adjustments
    - Suggested template updates
    """

    __tablename__ = "creative_calibration_runs"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="proposed")
    model_version: Mapped[str] = mapped_column(String(32), nullable=False)
    input_snapshot: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    successful_patterns: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    failure_patterns: Mapped[dict[str, Any]] = mapped_column(
        AI_JSON, nullable=False, default=dict
    )
    metrics: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    sample_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    rationale: Mapped[str | None] = mapped_column(String(2000), nullable=True)
    approved_by: Mapped[str | None] = mapped_column(String(64), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index(
            "ix_creative_calibration_workspace_status",
            "workspace_id",
            "status",
        ),
    )


# ---------------------------------------------------------------------------
# Creative Cost Event (C9)
# ---------------------------------------------------------------------------


class CreativeCostEvent(Base, TimestampMixin, WorkspaceMixin):
    """Creative cost event (C9): detailed cost tracking for creative generation.

    Every cost event is recorded with:
    - Model used and provider
    - Asset type and brief/product reference
    - Estimated vs actual cost
    - Cost category (generation, QC, calibration, etc.)

    Cost events are immutable once created - corrections create new events.
    """

    __tablename__ = "creative_cost_events"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    generation_run_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_generation_runs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    asset_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_studio_assets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    brief_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("creative_briefs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    product_id: Mapped[Uuid | None] = mapped_column(
        Uuid,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    asset_type: Mapped[str] = mapped_column(String(32), nullable=False)
    cost_category: Mapped[str] = mapped_column(
        String(32), nullable=False, default="generation"
    )
    estimated_cost: Mapped[Decimal] = mapped_column(
        Numeric(10, 4), nullable=False, default=Decimal("0")
    )
    actual_cost: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 4), nullable=True
    )
    currency: Mapped[str] = mapped_column(String(8), nullable=False, default="CNY")
    image_count: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    context: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index(
            "ix_cce_date",
            "workspace_id",
            "created_at",
        ),
        Index(
            "ix_cce_model",
            "workspace_id",
            "model",
        ),
        Index(
            "ix_cce_asset_type",
            "workspace_id",
            "asset_type",
        ),
        Index(
            "ix_cce_brief",
            "workspace_id",
            "brief_id",
        ),
        Index(
            "ix_cce_product",
            "workspace_id",
            "product_id",
        ),
        Index(
            "ix_cce_run",
            "generation_run_id",
        ),
        Index(
            "ix_cce_asset",
            "asset_id",
        ),
        Index(
            "ix_cce_brief_id",
            "brief_id",
        ),
        Index(
            "ix_cce_product_id",
            "product_id",
        ),
        Index(
            "ix_cce_model_name",
            "model",
        ),
        Index(
            "ix_cce_asset_type_name",
            "asset_type",
        ),
        Index(
            "ix_cce_cost_cat",
            "cost_category",
        ),
    )


# ---------------------------------------------------------------------------
# Creative Approval Request (C10)
# ---------------------------------------------------------------------------


class CreativeApprovalRequest(Base, TimestampMixin, WorkspaceMixin):
    """Creative approval request (C10): human-in-the-loop for high-risk operations.

    Approval requests are created automatically for:
    - High-cost generations (above budget threshold)
    - Bulk batch generation (many assets at once)
    - WooCommerce push operations
    - Calibration decisions

    Status flow: pending → approved/rejected → (optionally) executed
    """

    __tablename__ = "creative_approval_requests"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    request_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="pending", index=True)
    risk_level: Mapped[str] = mapped_column(String(16), nullable=False, default="medium")
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    context: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    estimated_cost: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    asset_count: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    requested_by: Mapped[str] = mapped_column(String(128), nullable=False, default="system")
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )
    approved_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approval_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    execution_result: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_car_workspace_status", "workspace_id", "status"),
        Index("ix_car_workspace_type", "workspace_id", "request_type"),
        Index("ix_car_workspace_risk", "workspace_id", "risk_level"),
    )


# ---------------------------------------------------------------------------
# Creative Automation Workflow (C11)
# ---------------------------------------------------------------------------


class CreativeAutomationWorkflow(Base, TimestampMixin, WorkspaceMixin):
    """Creative automation workflow (C11): automated creative production pipelines.

    Workflows define automated sequences of creative operations triggered by:
    - Manual trigger
    - Scheduled execution (daily, weekly, monthly)
    - Event-based (new product, brief created, asset generated)

    Workflow types:
    - ``batch_generation``: Generate multiple assets from a brief
    - ``ai_qc_pipeline``: Run AI QC on generated assets
    - ``template_refresh``: Refresh templates with new parameters
    - ``knowledge_sync``: Sync knowledge entries across workspaces
    - ``custom``: Custom workflow defined by steps
    """

    __tablename__ = "creative_automation_workflows"

    id: Mapped[Uuid] = mapped_column(Uuid, primary_key=True, default=lambda: uuid4())
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    workflow_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    trigger_type: Mapped[str] = mapped_column(String(16), nullable=False, default="manual")
    trigger_config: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="inactive", index=True)
    steps: Mapped[list[Any]] = mapped_column(AI_JSON, nullable=False, default=list)
    parameters: Mapped[dict[str, Any]] = mapped_column(AI_JSON, nullable=False, default=dict)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_run_status: Mapped[str | None] = mapped_column(String(16), nullable=True)
    total_runs: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    success_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    failure_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_by: Mapped[str] = mapped_column(String(128), nullable=False, default="system")
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_caw_workspace_status", "workspace_id", "status"),
        Index("ix_caw_workspace_type", "workspace_id", "workflow_type"),
        Index("ix_caw_workspace_trigger", "workspace_id", "trigger_type"),
    )
